#!/bin/bash
a=`cat storage`
a=$(($a + 8))
#case when the producer is finished
if((a>=100))
	then echo "from producer: Now I will take a rest!"
#adds 8 to the value in the file & executes consumer
else
	echo "from producer: current total is $a"
	echo $a > storage
	./consumer
fi
